ALTER TABLE "cameras" ADD COLUMN "faceDetectionThreshold" DOUBLE PRECISION NOT NULL DEFAULT 0.7;
ALTER TABLE "cameras" ADD COLUMN "faceRecognitionThreshold" DOUBLE PRECISION NOT NULL DEFAULT 0.9;
ALTER TABLE "cameras" ADD COLUMN "faceMinArea" INTEGER NOT NULL DEFAULT 500;
