/**
 * Database Module
 * Handles database connections and models using Prisma ORM
 *
 * TODO: Add database initialization function
 * TODO: Add database health checks
 * TODO: Add database query logging for debugging
 * TODO: Implement database transaction management
 */

import { prisma } from './client.js';

// Export Prisma client
export { prisma };

// Export generated types (generated by Prisma at build time)
// export type { Tenant, Camera, Event } from '@prisma/client';

export const dbModule = {
  /**
   * Initialize database connection
   * Check connection and run health checks
   */
  async initialize(): Promise<void> {
    try {
      await prisma.$queryRaw`SELECT 1`;
      console.info('✅ Database connection verified');
    } catch (error) {
      console.error('❌ Database connection failed:', error);
      throw error;
    }
  },

  /**
   * Disconnect from database
   * Call this on application shutdown
   */
  async disconnect(): Promise<void> {
    await prisma.$disconnect();
    console.info('✅ Database disconnected');
  },
};

